---
- hosts: "{{hostname}}"
  become: yes
  gather_facts: false
  vars:
    - apt_file: /etc/apt/sources.list.d/google-chrome.list
  tasks:
    - name: Add Google Chrome key
      shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - name: Add Google Chrome repo
      copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest="{{apt_file}}" owner=root group=root mode=644
    - name: Update apt cache
      apt: update_cache=yes
    - name: Install Google Chrome
      apt: pkg=google-chrome-stable state=latest
    - name: Install chrome driver
      shell: wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.92/linux64/chromedriver-linux64.zip
    - name: unzip install
      shell: sudo apt install unzip
    - name: unzip chromedriver
      shell: unzip chromedriver-linux64.zip
    - name: change chrome location
      shell: sudo mv chromedriver-linux64.zip/chromedriver /user/local/bin/chromedriver
